### ISSUE TITLE
Exit code unchanged when an error is encountered

### ISSUE THREAD

**Issue by tavianator** [uutils/findutils#27]
E.g.

```
$ mkdir foo
$ chmod -rwx foo
$ ./target/debug/find foo
foo
Error: foo: permission denied
$ echo $?
0
$ find foo
foo
find: ‘foo’: Permission denied
$ echo $?
1
```

**Comment by hanbings** [comment]
We handle errors caused by reading files in `process_dir()`, which conforms to the processing logic of GNU find. But internal errors that would cause `process_dir()` to be handled cannot be passed to the outer layer. Therefore adding a boolean error flag is used to pass a signal to the upper function to change the exit code when `process_dir()` has any error.

It might solve the problem, even if it's not very elegant :(
